# Chapter 1 - Python Exercise

## Package Import

In [1]:
import pandas as pd

## EDA

In [2]:
df = pd.read_csv("../data/PropertyFundInsample.csv")

In [3]:
df.describe()

,PolicyNum,Year,LnCoverage,BCcov,Premium,Freq,Deduct,y,lny,yAvg,...,TypeCity,TypeCounty,TypeMisc,TypeSchool,TypeTown,TypeVillage,AC00,AC05,AC10,AC15
count,5639.000000,5639.000000,5639.000000,5.639000e+03,5639.000000,5639.000000,5639.000000,5.639000e+03,5639.000000,5.639000e+03,...,5639.000000,5639.000000,5639.000000,5639.000000,5639.000000,5639.000000,5639.000000,5639.000000,5639.000000,5639.000000
mean,148880.491222,2007.979784,2.132881,3.728085e+07,14796.029793,1.109239,3364.869658,1.728730e+04,2.753088,9.291565e+03,...,0.140628,0.058166,0.107998,0.283206,0.172194,0.237808,0.463025,0.042383,0.057989,0.436602
std,15911.165649,1.415949,1.977179,1.034020e+08,25520.718048,8.549179,8273.670512,2.304627e+05,4.311270,1.975141e+05,...,0.347668,0.234078,0.310405,0.450596,0.377582,0.425779,0.498675,0.201480,0.233743,0.496008
min,120002.000000,2006.000000,-4.717555,8.937000e+03,9.000000,0.000000,500.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,138112.000000,2007.000000,0.785066,2.192556e+06,1612.500000,0.000000,500.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,150350.000000,2008.000000,2.429532,1.135357e+07,6578.000000,0.000000,1000.000000,0.000000e+00,0.000000,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,160619.000000,2009.000000,3.606218,3.682654e+07,18184.000000,1.000000,2500.000000,2.181825e+03,7.687917,1.519706e+03,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
max,180791.000000,2010.000000,7.801717,2.444797e+09,412328.000000,263.000000,100000.000000,1.292222e+07,16.374459,1.292222e+07,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000